import streamlit as st

st.markdown("<div class='bg-section'>About BrainGuard AI</div>", unsafe_allow_html=True)

st.subheader("The Vision")
st.write(
    "To democratize brain health data by turning a complex machine learning model into an "
    "interactive, public-facing dashboard. It serves two audiences: individuals looking to "
    "understand their modifiable risk factors, and clinicians who need an explainable, "
    "data-driven tool to back up their patient recommendations."
)

st.subheader("The Goal")
st.write(
    "An end-to-end data science application that allows users to input health/lifestyle "
    "metrics, receive a personalized dementia risk assessment, and view an interactive, "
    "localized breakdown of why they received that score using Explainable AI (XAI)."
)

st.subheader("The Core Question")
st.info(
    "\"Can an explainable machine learning model accurately assess dementia risk using "
    "purely non-invasive, modifiable lifestyle factors, and how can we effectively "
    "visualize these risk drivers to motivate patient behavior change?\""
)

st.markdown("---")

st.subheader("Disclaimer")
st.warning(
    "BrainGuard AI is an Artificial Intelligence based decision support system.\n\n"
    "The prediction generated by this application **is not a final medical diagnosis.**\n\n"
    "Always consult a qualified neurologist before making medical decisions."
)

st.markdown("---")
st.subheader("Contact")
st.info("support@brainguardai.com\n\nProject developed as part of a data science / AI course")

if st.session_state.get("role") is None:
    # Only reachable this way when opened from the Welcome screen's
    # "About" link -- the patient/clinic portals already have their own
    # sidebar nav back, so this button would be redundant there.
    st.markdown("---")

    def _go_home():
        st.session_state.show_about = False

    st.button("Return to Homepage", on_click=_go_home, type="primary")
